### ISSUE TITLE
Allow button styling customization

### ISSUE THREAD

**Issue by lipodido** [melistik/vaadin-grid-util#14]
As enhacement provide/allow buttons(view/edit/delete) styling customization
Cheers

**Comment by melistik** [comment]
i will add a custom styleName but generally you can already customize the display by css overwrite... i will add a documentation in some days...

**Comment by isccarrasco** [comment]
Hi, greate job...
Can this customization provide the posibility to use FontAwesome Resource instead a styleName ?
Thanks.

**Comment by melistik** [comment]
I already use FontAwesome Icons but I do it by css. The problem it's not that easy to add parameters per GridCellRenderer especially resources...

**Comment by isccarrasco** [comment]
Thanks...

I found a example from [Legioth](https://github.com/Legioth), used on the ["All about Grid Webinar"](https://github.com/Legioth/AllAboutGridWebinar), [the webinar](https://www.youtube.com/watch?v=BEnm9vG6eow)... he used an implementation of converter interface instead renderer. 

The implementation is in this [link](https://github.com/Legioth/AllAboutGridWebinar/blob/master/src/main/java/org/vaadin/allaboutgrid/BooleanToFontIconConverter.java).

**Comment by melistik** [comment]
Hehe, I know that we can do so for a single cell but in my case we don't only display an icon also the value is within this cell and different click-interactions are possible... I've hacked a bit the use of the GridCellRenderer in order to allow all these features within one cell...

**Comment by melistik** [comment]
I've added an example and updated the readme how you can change the icon of a button...
