### ISSUE TITLE
Extending GridUtil issue with private classes

### ISSUE THREAD

**Issue by nottallahx** [melistik/vaadin-grid-util#17]
Hello, I tried to extend your class to add a comboboxFilter that takes in a JPAContainer that represents lookup table.

the idea is that the box will show Display Value wile the Filter will apply the DB value. currently the nature of your private methods does not allow me to extend.

this more a request for enhancing or opening up the code more.

**Comment by melistik** [comment]
hi, i will publish within the next days the needed modifications!

**Comment by melistik** [comment]
hi, i've taken a look in the code and don't really know what you want to get opend ;) could you please give me a hint. For Example setComboBoxFilter already returns the ComboBox so that you can change the listing afterwards...

**Comment by melistik** [comment]
by the way with GridCellFilter.setCustomFilter you can do already what you want ;)
