### ISSUE TITLE
Filter header in Vaadin 7.6.0

### ISSUE THREAD

**Issue by ofbizbrazil** [melistik/vaadin-grid-util#18]
Hi all, 

After migrating my application to Vaadin 7.6.0, the header in grid filter is showing the components over the grid cell,  in this case is exceding the limit of header established. 

It is something related to CSS in my opinion. 

Cheers,

**Comment by melistik** [comment]
Hi,

could you please sent me an screenshot? I've upgraded my demo to 7.6.0 an hadn't any issues...

Thanks and best regards
