### ISSUE TITLE
Commit failed when update on grid

### ISSUE THREAD

**Issue by abdlkrmdlgr** [melistik/vaadin-grid-util#19]
Hi, 
comes from failed error when update grid. 
like this.
![screenshot_6](https://cloud.githubusercontent.com/assets/16466165/13137418/9857f100-d629-11e5-86c6-9be621b755d0.png)

but my datas keys {name,activation,questionOrder} but when commitin, my datas keys being null :(

**Comment by abdlkrmdlgr** [comment]
when I save without refresh BeanItemContainer committing success. when ı refresh beanItemContainer after commit, exception error comming.

**Comment by abdlkrmdlgr** [comment]
![screenshot_8](https://cloud.githubusercontent.com/assets/16466165/13137765/ecef0cce-d62b-11e5-93c2-f4143f3995b2.png)

**Comment by melistik** [comment]
Hi,
sorry for my late reply. Could you please sent me a full example so that I can see the issue?

Thanks and best regards
