### ISSUE TITLE
Change some methods as protected/public

### ISSUE THREAD

**Issue by fredy2015** [melistik/vaadin-grid-util#2]
Hi,

Could you change the methods layoutComponent() & clearFilter() in CellFilterComponent as public and replaceFilter(...) & removeFilter(...) in GridCellFilter as protected.
This change could allow to extend class GridCellFilter and add new type of fields as filter (for example like ResetButtonForTextField...)
Thanks in advance

**Comment by melistik** [comment]
will be part of next release
