### ISSUE TITLE
Support for non-standard theme size

### ISSUE THREAD

**Issue by phansson** [melistik/vaadin-grid-util#20]
Currently the in-cell-buttons have hardcoded size. This means that if you change the theme size then  the buttons can no longer fit in a cell and it looks ugly.

Try this in Valo Theme:

```
// Reduce font size to make everything smaller. There's no need to change
// $v-unit-size as well because it by default is derived from font-size. In other
// words: font-size controls everything !
$v-font-size: 12px;
```

and notice what it will do to your Grid. 

I'm assuming all themes somehow use `$v-font-size` so perhaps you can use that to scale the size of the buttons, margins, etc. ??

**Comment by melistik** [comment]
When you change your theme-sizes your need to overwrite the addon's default css-properties...
I cannot read out sass-variables from an addon
