### ISSUE TITLE
Left click not focussing filter input box

### ISSUE THREAD

**Issue by mahendran-ayyasamy** [melistik/vaadin-grid-util#24]
Filter input box can be tabbed in or right clicked in, but left clicking on them does not make them focused and is still blurred.

I think 

`filter.setTextFilter("grantNumber", true, false);
 filter.setTextFilter("applicationNumber", true, false)`

![image](https://cloud.githubusercontent.com/assets/18483990/16119430/6e820fea-33a9-11e6-8c31-308ff803ca10.png)

**Comment by melistik** [comment]
Hi, I didn't got your point. Could you please sent me a detailed code example?

**Comment by melistik** [comment]
missing example!
