### ISSUE TITLE
Vaadin column width auto-calculation fails if GridCellFilter is used

### ISSUE THREAD

**Issue by dominic-simplan** [melistik/vaadin-grid-util#26]
Hi,
 it seems as if the Vaadin auto-calculation of the column width fails if the GridCellFilter is used and there are more columns in the grid than can be displayed on the screen:
As can be seen in the following screenshot, the columns are way too wide for their content:
![filterwidthdefault](https://cloud.githubusercontent.com/assets/22240239/20272155/5d8f7ce4-aa8d-11e6-9f6d-48a044544cfc.png)

But if I set the width of the filter fields manually to 0, the auto-calculation works correctly:
![filterwidth0](https://cloud.githubusercontent.com/assets/22240239/20272154/5d8eb80e-aa8d-11e6-889b-932f93f8b879.png)

So it seems as if the default width settings for the Filter fields screw up the Vaadin auto-calculation? Is there any workaround/other way to solve this?

**Comment by melistik** [comment]
i didn't got your problem - could you please post an example code...

**Comment by melistik** [comment]
no example provided...

**Comment by dominic-simplan** [comment]
Hi,
sorry for the late reply. Let me try to rephrase the problem:

Adding the filter makes the Grid columns much wider than they need to be:
![grafik](https://user-images.githubusercontent.com/22240239/36423857-c00fa878-1641-11e8-825d-fd4c0f069f47.png)
Look at the "Length (mm)" column for example. The column width is cause by the two filter fields, while only considering the row values/row title, the column should be much smaller in width.

Is there any possibility that the filter fields adjust to the actual column width calculated by Vaadin instead of using a default width and therefore increasing the column width?
