### ISSUE TITLE
How to customize incorrect date format message for GridCellFilter?

### ISSUE THREAD

**Issue by dk2k** [melistik/vaadin-grid-util#32]
Brief: Hard coded english message for incorrect date specified in a date filter (please see fig).

![issue_311](https://cloud.githubusercontent.com/assets/13780045/21845652/77927e4e-d804-11e6-962b-19c505f4379c.png)

The string "Date format not recognized" originates from here:
http://https://dev.vaadin.com/svn/versions/6.5/src/com/vaadin/ui/DateField.java
private String defaultParseErrorMessage = "Date format not recognized";
In this class there is a setter provided.

Instances of this class are created when we call:

GridCellFilter claimsFilter = new GridCellFilter(claimsGrid);
claimsFilter.setDateFilter("createDateUI"); // DateFields get created here

We don't have means to pass our custom error string in Russian into this DateFilter.
We use version 7.7.6 of vaadin.

What are the options here?

I created a topic in the forum as well:  [https://vaadin.com/forum#!/thread/14936289](https://vaadin.com/forum#!/thread/14936289)

Thanks in advance

**Comment by melistik** [comment]
Hey, I've not written any translation by my own.
To localize this you can use the returned FieldGroup and get the DateField from it for example:

``` java
this.filter.setNumberFilter("bodySize", "smallest", "biggest");
FieldGroup dateFieldGroup = this.filter.setDateFilter("birthday", new SimpleDateFormat("yyyy-MMM-dd"), true);
((DateField) dateFieldGroup.getField(GridCellFilter.SMALLEST)).setParseErrorMessage("da ist was schief gegangen :)");
```

I guess this should solve your issue...

**Comment by dk2k** [comment]
Hi,
I didn't mean you had deteriorated the code, of course.
You suggestion works fine, please close this ticket. I didn't took into account I can use the returned value.
