### ISSUE TITLE
Possible addition of placeholders to NumberFilter

### ISSUE THREAD

**Issue by russellhoff** [melistik/vaadin-grid-util#4]
It would be great to let the developer introduce some kind of a "placeholder" in the filters, as to help the final user understand what the filter does.

For example, when I tried the NumberFilter, I didn't know why there were two fields to filter a single number (after some seconds I realised they were there as a range filter). It could be helpful in other filters, too.

Could it be possible as a future enhancement?

Thank you :)

**Comment by melistik** [comment]
Hi @russellhoff  this will be part of the next relase
