### ISSUE TITLE
edit/delete button style changed

### ISSUE THREAD

**Issue by lipodido** [melistik/vaadin-grid-util#5]
hi,
Why did the style of buttons edit/delete has been changed from normal (as visible in Project MD) to native buttons (as in demo),  they looked nicer before :-(
Regards

**Comment by melistik** [comment]
Hi that wasn't my plan but i've checked my code and since beginning the buttons had the class-name "v-nativebutton" maybe valo css has changed a bit? Could you please compare both dom-trees with the good lookin one and the demo. Please post when they differ and then i can check...

**Comment by lipodido** [comment]
unfortunately i couldn't reproduce the issue as you mentionned something has changed but what !!, And i confirme when i change (manually) the class to v-button eveything looks nice again.. 
![grid](https://cloud.githubusercontent.com/assets/7419872/7513637/06e4edd6-f4b6-11e4-9893-eae03f3e4d3e.PNG)

**Comment by melistik** [comment]
shure that you haven't changed anything? This is the way it look currently on my site...
![style-issue](https://cloud.githubusercontent.com/assets/1936030/7532180/49d549de-f564-11e4-85d9-9090f1bddf6d.jpg)

**Comment by lipodido** [comment]
you're right, i checked again with a clean project and it seem to be related to my project ( something about my css or something else !! ), if there is no plane to migrate to v-button you can close this issue
Regards

**Comment by melistik** [comment]
Ok, thanks for the feedback. Maybe i can add custom style-names later but current I cannot change because this will lead to different layouts in other projects :)
