### ISSUE TITLE
org.vaadin.gridutil.cell.GridCellFilter Serializable

### ISSUE THREAD

**Issue by ossd** [melistik/vaadin-grid-util#6]
GridCellFilter has to be serializable to be able to restart Tomcat. I thought it has to be serializable to be able to cluster the tomcat server?!

java.io.NotSerializableException: org.vaadin.gridutil.cell.GridCellFilter$2

**Comment by melistik** [comment]
The hole content of the GridCellFilter is not serializable I guess. It's a huge dynamic component with many layout elements that are also not all serialzable. What will help for development to change the settings as also recommended for vaadin development within context.xml of tomcat-settings to

```xml
<!-- Uncomment this to disable session persistence across Tomcat restarts -->
    <Manager pathname="" />
```

**Comment by ossd** [comment]
It is working when you make:
org.vaadin.gridutil.cell.GridCellFilter
org.vaadin.gridutil.cell.CellFilterComponent
Serializable. All member variables of this classes are serializable. Then serialization is working. Is it possible to add this two this two classes?
