### ISSUE TITLE
a new view/details button 

### ISSUE THREAD

**Issue by lipodido** [melistik/vaadin-grid-util#7]
as enhancement is it possible to add a third button (show or view or details   )  to existing button edit delete ? 
it will complete the toolkit :)
regards. 

http://fortawesome.github.io/Font-Awesome/icon/eye/

**Comment by melistik** [comment]
ok, i will add this one in next relase

**Comment by lipodido** [comment]
Merci :)

**Comment by melistik** [comment]
released 1.0.5
