### ISSUE TITLE
Provide MANIFEST.MF with OSGi meta-data

### ISSUE THREAD

**Issue by philippberger** [melistik/vaadin-grid-util#8]
Please use Maven Bundle Plugin to provide MANIFEST.MF with OSGi meta-data.

**Comment by melistik** [comment]
mhh ok could you maybe post the needed changes? I've never used osgi or the maven-bundle-plugin :)

**Comment by philippberger** [comment]
Have a look at: https://felix.apache.org/documentation/subprojects/apache-felix-maven-bundle-plugin-bnd.html

You simply add the maven-bundle-plugin without configuration I think:
            <plugin>
                <groupId>org.apache.felix</groupId>
                <artifactId>maven-bundle-plugin</artifactId>
                <extensions>true</extensions>
                <executions>
                    <execution>
                        <id>default-bundle</id>
                        <phase>process-classes</phase>
                        <goals>
                            <goal>manifest</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

**Comment by melistik** [comment]
thx - released 1.0.6 with your changes...
