### ISSUE TITLE
Why do "GridCellFilter#set*Filter"-Methods expect a String as column id?

### ISSUE THREAD

**Issue by philippberger** [melistik/vaadin-grid-util#9]
Why do "GridCellFilter#set*Filter"-Methods expect a String as column id?
Both, Vaadin Grid and Vaadin Filters are using Object for the property id or column id.

**Comment by melistik** [comment]
Mhh have you ever used something different then String?
Yes you are right it's Object normally - I can change it.
It hasn't any special reason to use String...

**Comment by philippberger** [comment]
It might get smoother to work with this addon in some cases.
Thanks.
